OptimumSource_Exam/OptimumSource_Exam/Controllers/ProblemTwo/ProbTwoOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OptimumSource_Exam.Controllers.ProblemTwo
{
    public class ProbTwoOrderController : Controller
    {
        //
        // GET: /ProbTwoOrder/

        public ActionResult Index()
        {
            return View();
        }

    }
}

OptimumSource_Exam/OptimumSource_Exam/Controllers/ProblemTwo/ProbTwoProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using OptimumSource_Exam.Models;
using OptimumSource_Exam.Services.ProblemTwo;

namespace OptimumSource_Exam.Controllers.ProblemTwo
{
    public class ProbTwoProductController : Controller
    {
        //
        // GET: /ProbTwoProduct/

        public ActionResult Product()
        {
            return View("~/Views/ProblemTwo/Product.cshtml");
        }

        public ActionResult AddProduct()
        {
            Session["IsProductNew"] = true;
            return View("~/Views/ProblemTwo/AddProduct.cshtml");
        }

        public ActionResult GetAllProducts(string sample)
        {
            try
            {
                List<ProbTwo_Products> productList = new List<ProbTwo_Products>();
                ProbTwo_ProductServices productServices = new ProbTwo_ProductServices();
                productList = productServices.GetAllProducts();

                var result = new ContentResult
                {
                    Content = JsonConvert.SerializeObject(productList),
                    ContentType = "application/json",
                };

                return result;

            }
            catch (Exception)
            {

                throw;
            }
        }

    }
}

OptimumSource_Exam/OptimumSource_Exam/Views/ProblemTwo/AddProduct.cshtml
@{
    ViewBag.Title = "AddProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <script src="~/Scripts/bootstrap-datetimepicker.js"></script>
</head>

<body>


    @if (Convert.ToBoolean(Session["IsProductNew"]))
    {
        <form method="post" id="AddProduct" enctype="multipart/form-data">

            <div class="panel panel-primary">
                <div class="panel-heading" style="margin-bottom:2%;">ADD PRODUCT</div>

                <div style="margin-right:20%; margin-left:20%;">
                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Code</span>
                        <input type="text" name="ProdCode" id="ProdCode" class="form-control" />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Description</span>
                        <input type="text" name="Description" id="Description" class="form-control" required />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Price</span>
                        <input type="text" name="Price" id="Price" class="form-control" required />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Is Discountable? <input type="checkbox" aria-label="..."></span>
                        <input type="text" name="Discount" id="Discount" class="form-control" required />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Date Added</span>
                        <input type="text" name="DateAdded" id="DateAdded" class="form-control" required />
                    </div>

                    <button type="button" class="btn btn-info btn-lg" id="Save" style="margin-bottom:4%;">Save</button>

                </div>
            </div>
        </form>

        <script type="text/javascript">
            $(document).ready(function () {

                $("#DateAdded").datetimepicker();

                $("#Description").focusout(function () {
                     $.ajax({
                            type: 'GET',
                            data: { ProdDesc: $("#Description").val() },
                            url: '@Url.Action("GenerateProductCode", "ProbOneProduct")',
                            success: function (result) {
                            $('#ProdCode').val(result);
                        }
                     });
                });

                $("#Save").click(function () {

                    BootstrapDialog.show({
                        message: 'Are you sure you want to Save Product?',
                        closable: false,
                        buttons: [
                        {
                            label: 'Save',
                            cssClass: 'btn-primary',
                            action: function () {
                                $("#AddProduct").submit();
                            }
                        },
                        {
                            label: 'Close',
                            action: function (dialogItself) {
                                dialogItself.close();
                            }
                        }
                        ]
                    });

                });


            });
        </script>

    }
    else
    {
        <form method="post" id="UpdateProduct" enctype="multipart/form-data">
            <div class="panel panel-primary">
                <div class="panel-heading" style="margin-bottom:2%;">ADD PRODUCT</div>

                <div style="margin-right:20%; margin-left:20%;">
                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Code</span>
                        <input type="text" name="UpdateProdCode" id="UpdateProdCode" class="form-control" disabled />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Description</span>
                        <input type="text" name="UpdateDescription" id="UpdateDescription" class="form-control" required />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Quantity</span>
                        <input type="text" name="UpdateQuantity" id="UpdateQuantity" class="form-control" required />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Bulk Order</span>
                        <input type="text" name="UpdateBulkOrder" id="UpdateBulkOrder" class="form-control" required />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Minimum Order</span>
                        <input type="text" name="UpdateMinOrder" id="UpdateMinOrder" class="form-control" required />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Price</span>
                        <input type="text" name="UpdatePrice" id="UpdatePrice" class="form-control" required />
                    </div>

                    <div class="input-group" style="margin-bottom:2%;">
                        <span class="input-group-addon">Critical Level</span>
                        <input type="text" name="UpdateCriticalLevel" id="UpdateCriticalLevel" class="form-control" required />
                    </div>

                    <button type="button" class="btn btn-info btn-lg" id="UpdateSave" style="margin-bottom:4%;">Save</button>

                </div>
            </div>
        </form>

        <script type="text/javascript">
                $(document).ready(function () {

                    $("#Description").focusout(function () {
                        $.ajax({
                            type: 'GET',
                            data: { ProdDesc: $("#Description").val() },
                            url: '@Url.Action("GenerateProductCode", "ProbOneProduct")',
                            success: function (result) {
                                $('#ProdCode').val(result);
                            }
                     });
                });

                $("#UpdateSave").click(function () {

                    BootstrapDialog.show({
                        message: 'Are you sure you want to Update this Product?',
                        closable: false,
                        buttons: [
                        {
                            label: 'Update',
                            cssClass: 'btn-primary',
                            action: function () {
                                $("#UpdateProduct").submit();
                            }
                        },
                        {
                            label: 'Close',
                            action: function (dialogItself) {
                                dialogItself.close();
                            }
                        }
                        ]
                    });

                });


            });
        </script>
    }



</body>

</html>

OptimumSource_Exam/OptimumSource_Exam/Views/ProblemTwo/Product.cshtml
@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int Id = 0;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/locale/bootstrap-table-zh-CN.min.js"></script>
</head>
<body>

    <form action="" method="post" id="ProductProbOne" enctype="multipart/form-data">
        @Html.Hidden("Product_Id", 0)
        <div class="panel panel-primary">
            <div class="panel-heading">Product</div>
            <div class="row" style="margin:1%;">
                <div id="toolbar">
                    <div class="form-inline" role="form">
                        <div class="form-group">
                            <input type="button" id="AddProduct" class="btn btn-default" onclick="location.href='@Url.Action("AddProduct", "ProbTwoProduct")'" value="Add Product" />
                        </div>

                        <div class="form-group">
                            <input type="button" id="Orders" class="btn btn-default" onclick="location.href='@Url.Action("Order", "ProbTwoOrder")'" value="Go to Cart" />
                        </div>
                    </div>
                </div>

                @*@Html.ActionLink("Problem1", "GetAllProducts", "ProductProbOne", null, new  {style="text-decoration:none;aria-hidden:true;", @class="glyphicon glyphicon glyphicon-cog" })*@

                <table id="table"
                       data-show-export="true"
                       data-show-columns="true"
                       data-toolbar="#toolbar"></table>

            </div>

        </div>
    </form>

    <script type="text/javascript">

        $(document).ready(function () {


             window.operateEvents = {
                'click .edit': function (e, value, row, index) {
                    //location.href = 'UpdateProduct?ProductId=' + row.Id;
                    BootstrapDialog.show({
                        message: 'Sorry, Still in Development',
                        closable: true,
                    });
                },
                'click .remove': function (e, value, row, index) {

                    @*BootstrapDialog.show({
                        message: 'Are you sure you want to Delete this Product?',
                        closable: false,
                        buttons: [
                        {
                            label: 'YES',
                            cssClass: 'btn-primary',
                            action: function (dialogItself) {

                                $.ajax({
                                    type: 'POST',
                                    data: { ProductId: row.Id },
                                    url: '@Url.Action("DeleteProduct", "ProbOneProduct")',
                                    success: function (result) {
                                        $('#table').bootstrapTable('refresh');
                                        dialogItself.close();
                                    }
                                });
                            }
                        },
                        {
                            label: 'Close',
                            action: function (dialogItself) {
                                dialogItself.close();
                            }
                        }
                        ]
                    });*@
                    BootstrapDialog.show({
                            message: 'Sorry, Still in Development',
                            closable: true,
                        });
                }
            }


            $('#table').bootstrapTable({
                url: '@Url.Action("GetAllProducts", "ProbTwoProduct")',
                //striped: true,
                pagination: true,
                method: 'post',
                search: true,
                locale: 'en-US',
                pageList: [50, 100, 'ALL'],
                pageSize: 100,
                height: 380,
                showRefresh: true,
                queryParams: function (p) {
                    return {
                        sample: "abc"
                        //uploadType_Id: $("#uploadType").val(),
                        //classification_Id: $("#classification").val(),
                        //isConsolidated: $("#consolidated").is(':checked')
                        //dateModified:  '@DateTime.Now'
                    }
                },
                columns: [
                {
                    field: 'Id',
                    title: 'Id',
                    sortable: true
                },
                {
                    field: 'ProductCode',
                    title: 'ProductCode',
                    sortable: true
                },
                {
                    field: 'ProductDescription',
                    title: 'ProductDescription',
                    sortable: true
                },
                {
                    field: 'Price',
                    title: 'Price',
                    sortable: true
                },
                {
                    field: 'IsDiscounted',
                    title: 'IsDiscounted',
                    sortable: true
                },
                {
                    field: 'Discount',
                    title: 'Discount',
                    sortable: true
                },
                {
                    field: 'DateAdded',
                    title: 'DateAdded',
                    sortable: true
                },
                {
                    field: 'CriticalLevel',
                    title: 'CriticalLevel',
                    sortable: true
                },
                {
                    title: 'Action',
                    events: operateEvents,
                    formatter: operateFormatter
                }

                ]
            });


            //$('#Search').click(function () {
            //    $('#table').bootstrapTable('refresh');
            //});

            function operateFormatter(value, row, index) {
                return [
                    '<a class="edit" href="javascript:void(0)" title="Edit" >   ',
                    '<i class="glyphicon glyphicon-pencil"></i>',
                    '</a>  ',
                    '<a class="remove" href="javascript:void(0)" title="Remove" >   ',
                    '<i class="glyphicon glyphicon-remove"></i>',
                    '</a>  '
                ].join('');
            }

        });

    </script>

</body>

</html>